### ISSUE TITLE
Project Complete 

### ISSUE THREAD

**Issue by capitalkind** [capitalkind/GameGame#1]
Completeness 4.5/5
Comfortability 3.5/5
Win: It works!
Challenge: This was tough, but a good learning experience. Halfway through I realized I was attacking the entire endeavour wrong and had to rethink my approach

**Comment by clay-reed-a** [comment]
Malcolm, 

This is awesome. It's so smooth!

I also think it's critical you were able to rethink your approach and start over. That's one of the hardest things to do but absolutely essential. 

I'm also very interested in your [recursive](https://en.wikipedia.org/wiki/Recursion_%28computer_science%29) implementation of the GameTimer. 

It took me a few seconds to figure out how it worked. 

Can you tell me: 
- How you knew to use recursion? 
- [How the recursion in `startGameTime` works?](https://mitpress.mit.edu/books/little-schemer)

Clay a
